#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 21 14:14:52 IST 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim testbench1_behav -key {Behavioral:sim_1:Functional:testbench1} -tclbatch testbench1.tcl -view /home/debleena/Thales/ReleaseMSI_bus/project_msi_bus/testbench1_behav.wcfg -log simulate.log"
xsim testbench1_behav -key {Behavioral:sim_1:Functional:testbench1} -tclbatch testbench1.tcl -view /home/debleena/Thales/ReleaseMSI_bus/project_msi_bus/testbench1_behav.wcfg -log simulate.log

